### ISSUE TITLE
TRP incompatable with BFA pre-patch update

### ISSUE THREAD

**Issue by Jaekton** [wow-rp-addons/Chomp#18]
My TRP-3 has been refusing to load because it says it's incompatible. i've tried looking at the F.A.Q. and the troubleshooting options... and I can't find anything to fix it. Please help.

![image](https://user-images.githubusercontent.com/41645160/43155174-b7b21d10-8f44-11e8-8aa4-cf2b3d8556a8.png)

**Comment by Solanya** [comment]
1. How did you end up here ? Total RP 3 is this way : https://github.com/Ellypse/Total-RP-3/issues

2. You need to update your addon to the latest version (which is currently 1.4.3). If you're using the Twitch app, make sure to restart it so it pulls up the latest versions, and make sure the right folder is selected (that it's not installing in the PTR/beta folder, or if you moved the game at some point, that it's not installing in the old folder)

If you're still having issues, please open a ticket on the repository I linked above or come on our Discord : http://discord.totalrp.com
