### ISSUE TITLE
kinds other than "WHISPER" and "CHANNEL" fail regardless of target value

### ISSUE THREAD

**Issue by Connor-Macleod** [wow-rp-addons/Chomp#19]
line #492 of public.lua asserts that target must be nil if the channel is not "WHISPER" or "CHANNEL" but the function later on (line #528) errors with any non string value of target.

Suggested fix: line #528 should be wrapped in `if kind == "WHISPER" then end` to only lookup player names if it's expecting a player name in the string

**Comment by ghost** [comment]
Thank you for the report. This is fixed, and in the v7 tag.
